version: "3.8"

services:
  freecad:
    #image: lscr.io/linuxserver/freecad:1.0.2
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - FreeCAD_VERSION=1.0.2
    container_name: freecad
    ports:
      - "3001:3000"
    volumes:
      - ./MeccanoWB:/opt/freecad/usr/Mod/MeccanoWB
    restart: unless-stopped