name: Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: lscr.io/linuxserver/freecad:latest
      options: --user root  # needed to install packages

    env:
      PYTHONPATH: /opt/freecad/usr/lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: pip3 install uv

      - name: Install project dependencies (including test group)
        run: uv sync --groups test

      - name: Run pytest
        run: pytest
